# Generated by Django 2.2.4 on 2019-10-01 16:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191001_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 1, 16, 58, 25, 264317, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
