# Generated by Django 2.2.4 on 2019-10-08 21:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20191001_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 8, 21, 44, 41, 942669, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
