# Generated by Django 2.2.4 on 2019-10-17 00:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20191016_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 0, 1, 29, 221961, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
