# Generated by Django 2.2.4 on 2019-10-21 01:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20191016_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 21, 1, 26, 53, 876090, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
