# Generated by Django 2.2.4 on 2019-10-21 01:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20191020_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 21, 1, 28, 29, 468448, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
