# Generated by Django 2.2 on 2019-10-25 00:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20191024_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 25, 0, 55, 8, 187201, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
