# Generated by Django 2.2 on 2019-10-25 00:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20191024_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 25, 0, 58, 24, 272323, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
