# Generated by Django 2.2 on 2019-10-26 19:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20191024_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 19, 54, 35, 151906, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
