# Generated by Django 2.2 on 2019-10-26 20:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20191026_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 20, 8, 37, 345343, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
