# Generated by Django 2.2 on 2019-10-29 03:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0057_auto_20191027_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 3, 4, 9, 600981, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
