# Generated by Django 2.2.6 on 2019-10-29 04:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0058_auto_20191028_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 4, 8, 23, 321865, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
