# Generated by Django 2.2.6 on 2019-11-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=80, verbose_name='Correo')),
                ('tipo', models.CharField(max_length=80, verbose_name='Tipo')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('saldo', models.SmallIntegerField(default=0, verbose_name='Saldo')),
                ('eafit', models.BooleanField(default=False, verbose_name='Miembro EAFIT')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['-created'],
            },
        ),
    ]
