# Generated by Django 2.2.4 on 2019-09-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=80, verbose_name='Correo')),
                ('tipo', models.CharField(max_length=80, verbose_name='Tipo')),
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usarios',
                'ordering': ['-created'],
            },
        ),
    ]
