# Generated by Django 2.2.6 on 2019-11-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tyc',
            field=models.BooleanField(default=False, verbose_name='Terminos y Condiciones'),
        ),
    ]
