# Generated by Django 2.2.4 on 2019-10-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20190927_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Identificador'),
        ),
    ]
