# Generated by Django 2.2.4 on 2019-10-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20191016_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Identificador'),
        ),
    ]
