# Generated by Django 2.2.4 on 2019-10-21 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20191020_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-created'], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
