# Generated by Django 2.2 on 2019-10-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20191020_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='nombre',
        ),
    ]
