# Generated by Django 2.2 on 2019-10-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_auto_20191026_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Identificador'),
        ),
    ]
