# Generated by Django 2.2.4 on 2019-10-08 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0004_auto_20190928_1805'),
        ('usuarios', '0003_auto_20191008_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trueque',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('direccionalidad', models.CharField(max_length=80, verbose_name='direccionalidad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.Libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
            ],
            options={
                'verbose_name': 'trueque',
                'verbose_name_plural': 'trueque',
                'ordering': ['-created'],
            },
        ),
    ]
