# Generated by Django 2.2.6 on 2019-11-12 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trueque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('direccionalidad', models.CharField(max_length=80, verbose_name='direccionalidad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
                ('libro', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='libros.Libro')),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
            ],
            options={
                'verbose_name': 'trueque',
                'verbose_name_plural': 'trueque',
                'ordering': ['-created'],
            },
        ),
    ]
