# Generated by Django 2.2 on 2019-10-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueque', '0003_auto_20191024_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trueque',
            name='id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False, verbose_name='Identificador'),
        ),
    ]
