# Generated by Django 2.2 on 2019-10-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueque', '0004_auto_20191026_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trueque',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Identificador'),
        ),
    ]
