# Generated by Django 2.2 on 2019-10-26 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trueque', '0005_auto_20191026_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trueque',
            name='libro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='libros.Libro'),
        ),
        migrations.AlterField(
            model_name='trueque',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
        ),
    ]
