# Generated by Django 2.2 on 2019-10-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueque', '0011_auto_20191026_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trueque',
            name='libro',
            field=models.IntegerField(verbose_name='Libro_id'),
        ),
        migrations.AlterField(
            model_name='trueque',
            name='usuario',
            field=models.BigIntegerField(verbose_name='Usuario_id'),
        ),
    ]
