# Generated by Django 2.2 on 2019-10-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueque', '0012_auto_20191026_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trueque',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador'),
        ),
    ]
