# Generated by Django 2.2 on 2019-10-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueque', '0013_auto_20191026_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trueque',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Identificador'),
        ),
    ]
