# Generated by Django 2.2 on 2019-10-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueque', '0017_auto_20191026_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trueque',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificador'),
        ),
    ]
