# Generated by Django 2.2 on 2019-10-26 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_auto_20191026_1547'),
        ('libros', '0007_auto_20191026_1547'),
        ('trueque', '0019_auto_20191026_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='trueque',
            name='libro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='libros.Libro'),
        ),
        migrations.AddField(
            model_name='trueque',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
        ),
    ]
