# Generated by Django 2.2.4 on 2019-09-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('titulo', models.CharField(max_length=80)),
                ('autor', models.CharField(max_length=80)),
                ('tipo', models.CharField(max_length=80)),
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
                'ordering': ['-created'],
            },
        ),
    ]
