# Generated by Django 2.2.6 on 2019-11-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('title', models.CharField(blank=True, default='', max_length=80, verbose_name='Titulo')),
                ('autor', models.CharField(blank=True, default='', max_length=80, verbose_name='Autor')),
                ('tipo', models.CharField(blank=True, default='', max_length=80, verbose_name='Tipo')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('editorial', models.CharField(blank=True, default='', max_length=80, verbose_name='Editorial')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
                'ordering': ['-created'],
            },
        ),
    ]
