# Generated by Django 2.2.4 on 2019-09-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='titulo',
        ),
        migrations.AddField(
            model_name='libro',
            name='title',
            field=models.CharField(default=' ', max_length=80, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=80, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='tipo',
            field=models.CharField(max_length=80, verbose_name='Tipo'),
        ),
    ]
