# Generated by Django 2.2.4 on 2019-09-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20190914_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Titulo'),
        ),
    ]
