# Generated by Django 2.2.4 on 2019-10-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_auto_20190928_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.CharField(default='', max_length=80, verbose_name='Editorial'),
        ),
    ]
