# Generated by Django 2.2 on 2019-10-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_auto_20191026_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificador'),
        ),
    ]
