# Generated by Django 2.2 on 2019-10-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0007_auto_20191026_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador'),
        ),
    ]
