# Generated by Django 2.2 on 2019-10-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0008_auto_20191026_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Identificador'),
        ),
    ]
